[mypy]
# Specify the target Python version
python_version = 3.11

# Add the 'src' directory to the search path for modules
mypy_path = src

# Ensure strict type checking where possible
strict = False

# Ignore missing imports for libraries that don't have type stubs
ignore_missing_imports = True

# Explicitly exclude the venv directory
exclude = venv/|.venv/

[mypy-aiogram.*]
ignore_missing_imports = True

[mypy-pymongo.*]
ignore_missing_imports = True
